name: get api
on: push
permissions:
 packages: write
 
env:
 pkg: "docker"

jobs:
 all:
  runs-on: self-hosted
  
  steps:
   - name: Login to GitHub container Registry
     run: |          
          curl  -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/orgs/cppkg/packages\?package_type=\container
