name: get api
on: workflow_dispatch

permissions:
 packages: write
 
env:
 pkg: "docker"

jobs:
 all:
  runs-on: self-hosted
  
  steps:
   - name: Login to GitHub container Registry
     run: |
          curl -H "Authorization: Bearer ${{ secrets.RW_PAT }}" "https://api.github.com/orgs/cppkg/packages"
