name: docker pull
on: workflow_dispatch

permissions:
 packages: write
 
env:
 pkg: "docker"

jobs:
 all:
  runs-on: self-hosted
  
  steps:
   - name: Login to GitHub container Registry
     run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
   - name: Build the Docker image
     run: docker pull ghcr.io/cppkg/busybbox:l1
